services:
  - type: web
    name: Portfolio
    env: python
    buildCommand: 
      - pip install -r requirements.txt
      - python manage.py collectstatic --noinput
    startCommand: gunicorn Portfolio.wsgi
