# Generated by Django 5.1.2 on 2024-10-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Database', 'Database'), ('Data Visualization', 'Data Visualization'), ('Aiml', 'Aiml'), ('Other', 'Other'), ('soft_skills', 'soft_skills')], default='Other', max_length=100),
        ),
    ]
