# Generated by Django 5.1.2 on 2024-10-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
