# Generated by Django 5.1.2 on 2024-10-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skills',
            new_name='skills_name',
        ),
    ]
