# Generated by Django 5.1.2 on 2024-10-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_rename_skills_skill_skills_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('PROGRAMMING', 'PROGRAMMING'), ('DATABASE', 'DATABASE'), ('Aiml', 'Aiml'), ('DATA VISUALIZATION', 'DATA VISUALIZATION'), ('OTHERS', 'OTHERS'), ('SOFT SKILLS', 'SOFT SKILLS')], default='OTHERS', max_length=100),
        ),
    ]
