# Generated by Django 5.1.2 on 2024-10-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='last_date',
            field=models.DateField(blank=True),
        ),
    ]
