# Generated by Django 5.1.2 on 2024-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_alter_experience_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
