# Generated by Django 5.1.2 on 2024-10-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_alter_experience_last_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='experience',
            name='description2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='experience',
            name='description3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='experience',
            name='description4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='experience',
            name='description5',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
