# Generated by Django 5.1.2 on 2024-10-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_rename_description_experience_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
