# Generated by Django 5.1.2 on 2024-10-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_alter_experience_description2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('school_or_college', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
    ]
