# Generated by Django 5.1.2 on 2024-10-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
