# Generated by Django 5.1.2 on 2024-10-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_alter_academic_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='marksheet',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
