# Generated by Django 5.1.2 on 2024-10-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_academic_marksheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='marksheet',
        ),
    ]
