# Generated by Django 5.1.2 on 2024-10-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_remove_academic_marksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_url', models.URLField()),
                ('description1', models.CharField(max_length=255)),
                ('description2', models.CharField(max_length=255)),
                ('description3', models.CharField(max_length=255)),
            ],
        ),
    ]
