# Generated by Django 5.1.2 on 2024-11-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0019_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.URLField(),
        ),
    ]
