# Generated by Django 5.1.2 on 2024-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0020_alter_certificate_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.URLField(max_length=1000),
        ),
    ]
